# Generated by Django 3.2 on 2021-05-13 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('imie', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('nazwisko', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('profilimg', models.ImageField(blank=True, default='media/1.jpg', null=True, upload_to='media/profiles/')),
                ('opis', models.TextField(blank=True)),
                ('kod', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('strona', models.CharField(blank=True, default='np www.mojadomena.pl', max_length=255, null=True)),
                ('telefon', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('profesja', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('miasto', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('port1', models.ImageField(blank=True, default='media/1.jpg', null=True, upload_to='media/portfolio/', verbose_name='galeria zdjęcie nr 1')),
                ('port2', models.ImageField(blank=True, default='media/1.jpg', null=True, upload_to='media/portfolio/', verbose_name='galeria zdjęcie nr 2')),
                ('port3', models.ImageField(blank=True, default='media/1.jpg', null=True, upload_to='media/portfolio/', verbose_name='galeria zdjęcie nr 3')),
                ('port4', models.ImageField(blank=True, default='media/1.jpg', null=True, upload_to='media/portfolio/', verbose_name='galeria zdjęcie nr 4')),
                ('port5', models.ImageField(blank=True, default='media/1.jpg', null=True, upload_to='media/portfolio/', verbose_name='galeria zdjęcie nr 5')),
                ('kategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='listy.category', verbose_name='Kategoria')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profile',
            },
        ),
    ]
